- hosts: localhost
  connection: local
  gather_facts: no    # 実行前に対象サーバの情報を収集する
  become: no
  vars:
    users:
      - { name: saxsir }
    yum_packages:
      - { name: zsh }
      - { name: git }
      - { name: go }
  tasks:
    - name: update yum
      yum: name=* state=latest
    - name: install yum packages
      yum: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
      with_items: "{{ yum_packages }}"

